//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Emporium.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table
    {
        public int TableId { get; set; }
        public int TableNo { get; set; }
        public System.DateTime TimeStarted { get; set; }
        public decimal BillAmount { get; set; }
        public int Pax { get; set; }
        public int UserId { get; set; }
    
        public virtual User User { get; set; }
    }
}
